/*
Assumptions:
    - Data warehouse already exists
    - Database "SPOTIFY_PIPELINE" and schemas, "RAW", "METADATA", "AUTH",
      "STAGING", "INTERMEDIATE", and "MART" from setup.sql already exist
    - This file is run with role ACCOUNTADMIN/SYSADMIN/SECURITYADMIN
*/
CREATE ROLE IF NOT EXISTS SPOTIFY_PIPELINE_ROLE;

GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE SPOTIFY_PIPELINE_ROLE;
GRANT USAGE ON DATABASE SPOTIFY_PIPELINE TO ROLE SPOTIFY_PIPELINE_ROLE;

GRANT USAGE ON SCHEMA SPOTIFY_PIPELINE.RAW TO ROLE SPOTIFY_PIPELINE_ROLE;
GRANT SELECT, INSERT ON FUTURE TABLES IN SCHEMA SPOTIFY_PIPELINE.RAW TO ROLE SPOTIFY_PIPELINE_ROLE;
GRANT SELECT, INSERT ON ALL TABLES IN SCHEMA SPOTIFY_PIPELINE.RAW TO ROLE SPOTIFY_PIPELINE_ROLE;

GRANT USAGE ON SCHEMA SPOTIFY_PIPELINE.METADATA TO ROLE SPOTIFY_PIPELINE_ROLE;
GRANT SELECT, INSERT, UPDATE ON FUTURE TABLES IN SCHEMA SPOTIFY_PIPELINE.METADATA TO ROLE SPOTIFY_PIPELINE_ROLE;
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA SPOTIFY_PIPELINE.METADATA TO ROLE SPOTIFY_PIPELINE_ROLE;

GRANT USAGE ON SCHEMA SPOTIFY_PIPELINE.AUTH TO ROLE SPOTIFY_PIPELINE_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA SPOTIFY_PIPELINE.AUTH TO ROLE SPOTIFY_PIPELINE_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA SPOTIFY_PIPELINE.AUTH TO ROLE SPOTIFY_PIPELINE_ROLE;

GRANT USAGE ON SCHEMA SPOTIFY_PIPELINE.STAGING TO ROLE SPOTIFY_PIPELINE_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA SPOTIFY_PIPELINE.STAGING TO ROLE SPOTIFY_PIPELINE_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA SPOTIFY_PIPELINE.STAGING TO ROLE SPOTIFY_PIPELINE_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA SPOTIFY_PIPELINE.STAGING TO ROLE SPOTIFY_PIPELINE_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA SPOTIFY_PIPELINE.STAGING TO ROLE SPOTIFY_PIPELINE_ROLE;
GRANT CREATE TABLE, CREATE VIEW ON SCHEMA SPOTIFY_PIPELINE.STAGING TO ROLE SPOTIFY_PIPELINE_ROLE;

GRANT USAGE ON SCHEMA SPOTIFY_PIPELINE.INTERMEDIATE TO ROLE SPOTIFY_PIPELINE_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA SPOTIFY_PIPELINE.INTERMEDIATE TO ROLE SPOTIFY_PIPELINE_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA SPOTIFY_PIPELINE.INTERMEDIATE TO ROLE SPOTIFY_PIPELINE_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA SPOTIFY_PIPELINE.INTERMEDIATE TO ROLE SPOTIFY_PIPELINE_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA SPOTIFY_PIPELINE.INTERMEDIATE TO ROLE SPOTIFY_PIPELINE_ROLE;
GRANT CREATE TABLE, CREATE VIEW ON SCHEMA SPOTIFY_PIPELINE.INTERMEDIATE TO ROLE SPOTIFY_PIPELINE_ROLE;

GRANT USAGE ON SCHEMA SPOTIFY_PIPELINE.MART TO ROLE SPOTIFY_PIPELINE_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA SPOTIFY_PIPELINE.MART TO ROLE SPOTIFY_PIPELINE_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA SPOTIFY_PIPELINE.MART TO ROLE SPOTIFY_PIPELINE_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA SPOTIFY_PIPELINE.MART TO ROLE SPOTIFY_PIPELINE_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA SPOTIFY_PIPELINE.MART TO ROLE SPOTIFY_PIPELINE_ROLE;
GRANT CREATE TABLE, CREATE VIEW ON SCHEMA SPOTIFY_PIPELINE.MART TO ROLE SPOTIFY_PIPELINE_ROLE;


GRANT ROLE SPOTIFY_PIPELINE_ROLE TO USER ishanb30;
