/*
Assumptions:
    - Refresh token insertion into AUTH.TOKENS is a manual, one-time-per-token
      process, not part of the pipeline - Spotify's OAuth consent screen
      requires a human in a browser, so this step can never be automated.
      Before the first pipeline run (and again after each re-auth, roughly
      every 180 days, prompted by a watchdog alert at ~160 days), run auth.py
      to obtain a fresh refresh token, then insert it here with ISSUE_DATE
      set to the actual moment it was issued.
*/
CREATE DATABASE IF NOT EXISTS SPOTIFY_PIPELINE;

CREATE SCHEMA IF NOT EXISTS SPOTIFY_PIPELINE.RAW;
CREATE SCHEMA IF NOT EXISTS SPOTIFY_PIPELINE.METADATA;
CREATE SCHEMA IF NOT EXISTS SPOTIFY_PIPELINE.AUTH;
CREATE SCHEMA IF NOT EXISTS SPOTIFY_PIPELINE.STAGING;
CREATE SCHEMA IF NOT EXISTS SPOTIFY_PIPELINE.INTERMEDIATE;
CREATE SCHEMA IF NOT EXISTS SPOTIFY_PIPELINE.MART;


CREATE TABLE IF NOT EXISTS SPOTIFY_PIPELINE.RAW.RECENTLY_PLAYED(
    RUN_ID VARCHAR(36),
    RAW_DATA VARIANT,
    LOADED_AT TIMESTAMP_NTZ DEFAULT SYSDATE()
);

CREATE TABLE IF NOT EXISTS SPOTIFY_PIPELINE.METADATA.PIPELINE_RUNS(
    RUN_ID VARCHAR(36) PRIMARY KEY,
    RUN_START TIMESTAMP_TZ,
    RUN_END TIMESTAMP_TZ,
    WATERMARK_TIMESTAMP TIMESTAMP_TZ,
    RUN_STATUS VARCHAR(9)
);

CREATE TABLE IF NOT EXISTS SPOTIFY_PIPELINE.AUTH.TOKENS(
    REFRESH_TOKEN VARCHAR NOT NULL,
    ISSUE_DATE TIMESTAMP_TZ
);



