
name: 'Spotify Pipeline'
on:
  workflow_dispatch:
  schedule:
    - cron: '17 */2 * * *'
      timezone: 'UTC'
jobs:
  spotify_pipeline:
    runs-on: ubuntu-latest
    timeout-minutes: 90
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-python@v7
        with:
          python-version: '3.12.5'
      - run: pip install -r requirements.txt
      - run: python run.py
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          ACCOUNT_IDENTIFIER: ${{ secrets.ACCOUNT_IDENTIFIER }}
          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          ROLE: 'SPOTIFY_PIPELINE_ROLE'
          HEARTBEAT_URL: ${{ secrets.HEARTBEAT_URL }}
          DATA_WAREHOUSE: 'COMPUTE_WH'
          DATABASE: 'SPOTIFY_PIPELINE'
concurrency:
  group: 'spotify-pipeline'
  cancel-in-progress: false


